export const metadata = {
  title: 'Nwigiri Next.js Shopping app',
  description: 'Generated by create next app',
  icons: {
    icon: 'null',
  },
};

export default function Home() {
  return (
    <div>
      hi
    </div>
  );
}