// app/page.jsx
import ClientDashboard from './components/Dynamic';

export const metadata = {
  title: 'Nwigiri Next.js Shopping app',
  description: 'Generated by create next app',
  icons: {
    icon: 'null',
  },
  link: [
    {
      rel: 'stylesheet',
      href: 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined',
    },
  ],
};

export default function Dashboard() {
  return (
    <div>
      <ClientDashboard />
    </div>
  );
}